name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install vite
        run: npm install --save-dev vite

      - name: Install @vitejs/plugin-vue
        run: npm install --save-dev @vitejs/plugin-vue

      - name: Install vite-plugin-vuetify
        run: npm install --save-dev vite-plugin-vuetify

      - name: Install vue-toast-notification
        run: npm install --save vue-toast-notification

      - name: Install @mdi/font
        run: npm install --save @mdi/font

      - name: Install vuex
        run: npm install --save vuex

      - name: Install webfontloader
        run: npm install --save webfontloader

      - name: Install keyboard-css
        run: npm install --save keyboard-css

      - name: Install @types/better-sqlite3
        run: npm install --save-dev @types/better-sqlite3

      - name: Set GitHub Personal Access Token
        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

      - name: Install snapcraft
        run: sudo snap install snapcraft --classic

      - name: Build
        run: npm run app:build

      - name: Electron Builder
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          projectDir: .
          config: .electron-builder.yml
          outputDir: dist_electron

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: svenstaro/upload-release-action@2.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist_electron/your-app-file
          asset_name: your-app-file
          tag: ${{ github.ref }}
          overwrite: true
          body: "Release of version ${{ github.ref }}"
