name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install vite
        run: npm install --save-dev vite

      - name: Install @vitejs/plugin-vue
        run: npm install --save-dev @vitejs/plugin-vue

      - name: Build
        run: npm run app:build

      - name: Electron Builder
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          # The path to your project directory
          projectDir: .
          # The path to the Electron Builder configuration file
          config: .electron-builder.yml
          # The path to the directory containing the packaged app
          outputDir: dist_electron
